name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main:
    name: Run main Job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Dependency Review"
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3

      - name: "Dependency Review"
        if: github.event_name != 'pull_request'
        uses: actions/dependency-review-action@v3
        with:
          base-ref: ${{ github.event.base_ref }}

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.2
        with:
          cosign-release: "v2.1.1"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "go"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache-dependency-path: ui/package-lock.json
          cache: "npm"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # We don't want to build the entire frondend, so we are using standalone npm ci
      - name: Install frontend packages (w/o go generate)
        working-directory: ./ui
        run: |
          npm ci

      - name: Install ESLint and Prettier
        working-directory: ./ui
        run: |
          npm install eslint@8.10.0
          npm install prettier@3.0.3
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        working-directory: ./ui
        run: npx --yes eslint . --config .eslintrc.cjs --ignore-path .gitignore --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ui/eslint-results.sarif
          wait-for-processing: true

      - name: Run Prettier
        working-directory: ui
        run: npx --yes prettier src/

      - name: Download go dependencies
        run: go mod download

      - name: Build Frontend
        run: go generate ./...

      - name: Go build
        run: go build -x -o ./url-shortener .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:go"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.3.0
        with:
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
