name: Main

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  main:
    name: Run main Job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3

      - name: 'Dependency Review'
        if: github.event_name != 'pull_request'
        uses: actions/dependency-review-action@v3
        with:
          base-ref: ${{ github.event.before }}
          head-ref: ${{ github.event.after }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

